version: '3'
services:
  app:
    build: .
    ports:
    - '3000:3000'
    volumes:
    - .:/app
    command: npm start
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:letmein12345@db:3307/full_stack_project
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=letmein12345
      - MYSQL_DATABASE=full_stack_project
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3307:3306'
volumes:
  db_data: